name: clang-tidy-review

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          clang-18 \
          clang-tidy-18 \
          g++ \
          libeigen3-dev \
          libzip-dev \
          zipcmp \
          zipmerge \
          ziptool \
          zlib1g-dev \
          ninja-build

    - name: Run CMake
      run: |
        cmake -S . -B build -DTRX_ENABLE_CLANG_TIDY=ON \
          -DCMAKE_C_COMPILER=clang-18 \
          -DCMAKE_CXX_COMPILER=clang++-18

    - name: Run clang-tidy
      run: |
        run-clang-tidy-18 -p build src examples
